# Generated by Django 6.1.1 on 2026-09-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.CharField(choices=[('ALIANZAS', 'Alianzas'), ('COMPROMISO', 'Compromiso'), ('RELOJ', 'Reloj'), ('COLLAR', 'Collar')], max_length=20)),
                ('material', models.CharField(choices=[('TUNGSTENO', 'Tungsteno'), ('PLATA', 'Plata Ley 925'), ('TITANIO', 'Titanio'), ('ACERO', 'Acero 316l')], max_length=20)),
                ('gama', models.CharField(choices=[('ALTA', 'Gama Alta'), ('MEDIA', 'Gama Media'), ('BAJA', 'Gama Baja')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('imagen', models.ImageField(upload_to='productos')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO', 'Monto')], max_length=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cantidad_minima', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones_directas', to='appInventory.producto')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_asociados', to='appInventory.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='PromocionCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, choices=[('ALIANZAS', 'Alianzas'), ('COMPROMISO', 'Compromiso'), ('RELOJ', 'Reloj'), ('COLLAR', 'Collar')], max_length=20, null=True)),
                ('material', models.CharField(blank=True, choices=[('TUNGSTENO', 'Tungsteno'), ('PLATA', 'Plata Ley 925'), ('TITANIO', 'Titanio'), ('ACERO', 'Acero 316l')], max_length=20, null=True)),
                ('gama', models.CharField(blank=True, choices=[('ALTA', 'Gama Alta'), ('MEDIA', 'Gama Media'), ('BAJA', 'Gama Baja')], max_length=20, null=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='appInventory.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=5)),
                ('genero', models.CharField(choices=[('MUJER', 'Mujer'), ('HOMBRE', 'Hombre'), ('UNISEX', 'Unisex')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='appInventory.producto')),
            ],
        ),
    ]
