# Generated by Django 6.1.1 on 2026-09-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appInventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
