# Generated by Django 6.1.1 on 2026-10-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInventory', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
